name: Build and Publish Android Pre-Release APKs

on:
  workflow_dispatch:

permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag_version_name: ${{ steps.set_version.outputs.tag_version_name }}
    steps:
      - name: 下载代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 设置Java编译环境
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: 编译安卓
        run: |
          rootDir=$(pwd)
          # 配置版本号和版本名
          versionName=$(grep 'versionName' "${rootDir}/app/build.gradle" | sed -n 's/.*versionName "\([^"]*\)".*/\1/p' |awk '{print $2}' |  tr -d '[:space:]')
          versionCode=$(grep 'versionCode' "${rootDir}/app/build.gradle" |  awk '{print $2}' | tr -d '[:space:]')
          # 设置标签名，使用 '+' 分隔构建元数据
          tagVersionName="v${versionName}+commit.$(date +'%Y%m%d%H%M%S')"
          echo "tag_version_name=${tagVersionName}" >> $GITHUB_OUTPUT
          echo "${tagVersionName}" >> ${{github.workspace}}/tagVersionName.txt
          echo "${versionCode}" >> ${{github.workspace}}/versionCode.txt
          # 配置运行权限
          chmod +x "${rootDir}/gradlew"
          # 创建release目录
          mkdir "${rootDir}/release/"
          # 构建二进制文件
          "${rootDir}/gradlew" app:buildCMakeRelWithDebInfo
          # 优先构建xposed版本
          for flavor in xposed ; do
            "${rootDir}/gradlew" "assemble${flavor^}Release"
            cp "${rootDir}/app/build/outputs/apk/${flavor}/release/app.apk" "${rootDir}/release/app-${flavor}.apk"
          done
        id: set_version
      - name: 上传 APK 到 artifact
        uses: actions/upload-artifact@v3
        with:
          name: temp-apk
          path: ${{github.workspace}}/release/
      - name: 打包脚本
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            ${{github.workspace}}/tagVersionName.txt
            ${{github.workspace}}/versionCode.txt
            ${{github.workspace}}/.github/workflows/upload.py
            ${{github.workspace}}/.github/workflows/configuration.json
